version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Greenwiz raw date source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez/ We have one row per products_id found in each orders_id
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign to product
          - name: revenue
            description: amount paid by the customer to purchase the product, revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased by this order
        tests:
              - unique:
                  column_name: "(orders_id || '_' || pdt_id)"
        freshness:    
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: the primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping__fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse
          - name: ship__cost
            description: the shipping cost paid by Greenweez to the carrie/transporter

